DEFAULT_WALKING_RADIUS_M = 400.0
MAX_WALKING_RADIUS_M = 2000.0

AVERAGE_WALKING_SPEED_MPS = 1.4
AVERAGE_BUS_SPEED_MPS = 13.9
AVERAGE_METRO_SPEED_MPS = 22.2

DEFAULT_DWELL_TIME_S = 30
DEFAULT_TRANSFER_PENALTY_S = 180

MAX_TRANSFERS_DEFAULT = 3
MAX_JOURNEY_CANDIDATES = 3

TICKET_EXPIRY_HOURS = 4
QR_PAYLOAD_EXPIRY_HOURS = 4

OSRM_TIMEOUT_S = 10.0
NOMINATIM_TIMEOUT_S = 10.0
NOMINATIM_RATE_LIMIT_DELAY_S = 1.0

GEOCODE_CACHE_TTL_S = 86400
ROUTE_GEOMETRY_CACHE_TTL_S = 86400
WALKING_DISTANCE_CACHE_TTL_S = 3600

DEFAULT_TIMEZONE = "Asia/Karachi"
CURRENCY = "PKR"

DEFAULT_BASE_FARE = 50.0
DEFAULT_PER_LEG_FARE = 20.0

SIMULATION_TICK_INTERVAL_S = 30
VEHICLE_POSITION_RETENTION_HOURS = 24